### ISSUE TITLE
task failed to collect processes metrics

### ISSUE THREAD

**Issue by imvisiontech** [intelsdi-x/snap-plugin-collector-processes#10]
Hi,
I am testing the snap-plugin-collector-processes.
I called the following commands:

./snapctl plugin load /home/shirley/temp/snap/plugin/snap-plugin-publisher-rabbitmq
./snapctl plugin load /home/shirley/temp/snap/plugin/snap-plugin-collector-processes
./snapctl task create -t /home/shirley/temp/snap/examples/tasks/processes-rabbitmq.json

and the task fails with the following error:
CollectMetrics call error : open /proc/1/io: permission denied

I tried to run the plugin and task as super user but it didn't help.
Do I need to add some configuration inforamtion to enable access?

thanks!

processes-rabbitmq.json file content:
{
    "version": 1,
    "schedule": {
        "type": "simple",
        "interval": "1s"
    },
    "workflow": {
        "collect": {
            "metrics": {
                "/intel/procfs/processes/running": {},
                "/intel/procfs/processes/stopped": {},
                "/intel/procfs/processes/waiting": {}
            },
            "config": {},
            "process": null,
            "publish": [
                {
					"plugin_name": "rabbitmq",
                    "config": {
						"address": "10.0.0.203:5672",
                        "exchange_name": "snap",
                        "routing_key": "meminfo",
                        "exchange_type": "direct"
                    }
                }
            ]
        }
    }
}

**Comment by jcooklin** [comment]
Hi @imvisiontech,

Did you start snapd as root?

**Comment by imvisiontech** [comment]
thanks, I already realized that :)

**Comment by marcin-krolik** [comment]
@imvisiontech : Since your problem was resolved, can we close this issue?
