### ISSUE TITLE
Path to procfs is not configurable

### ISSUE THREAD

**Issue by elemoine** [intelsdi-x/snap-plugin-collector-processes#11]
The path to procfs is currently [hardcoded](https://github.com/intelsdi-x/snap-plugin-collector-processes/blob/901c7da2b8835d12077cce9684442205b3fe1e10/processes/procstat.go#L42
) to /proc. This makes it hard (if even possible) to use the plugin when snapd is run in a Docker container.

**Comment by marcin-krolik** [comment]
Fixed with #12

**Comment by candysmurf** [comment]
@elemoine, the fix is merged. Do you mind to verify if it meets your needs? thanks!

**Comment by elemoine** [comment]
Thanks @candysmurf. I will test it, but I think we can close this issue.
