### ISSUE TITLE
Plugin metadata is not correct

### ISSUE THREAD

**Issue by elemoine** [intelsdi-x/snap-plugin-collector-processes#13]
`pluginVendor` is [used](https://github.com/intelsdi-x/snap-plugin-collector-processes/blob/master/processes/processes.go#L122) as the plugin name in the plugin metadata, resulting in the following output for `snapctl plugin list`:

```
NAME             VERSION         TYPE            SIGNED          STATUS          LOADED TIME
intel            4               collector       false           loaded          Tue, 14 Jun 2016 09:21:49 UTC
```

`NAME` should be `processes`.

**Comment by marcin-krolik** [comment]
Fixed with #15
