### ISSUE TITLE
Inquiry about roadmap implementation

### ISSUE THREAD

**Issue by jtlisi** [intelsdi-x/snap-plugin-collector-processes#16]
I'm curious about the planned implementation of:
- [ ] Gathering task status from `"/proc/<pid>/task"`

Mainly in regards to how the pid will be specified in the task configuration. I was interested in a config at that specifies the paths to a .pid files which are used to get the pid of the process you wish to collect metrics on. An alternative would be specifying a process name. 
An example would be:
`"config": {`
`"file": "/tmp/app.pid,/tmp/app2.pid",`
`"process": "snapd"`
`}`

Both file and process would be comma separated lists so you could specify multiple metrics. If anyone has any thought's I'd love to hear them. Also, I would be interested in putting in a pull request if these changes are ok.

**Comment by nanliu** [comment]
Sorry for taking a long time looping back to this. Do you have a branch that implements this idea? I can see this being interesting to only track specific service processes.

**Comment by jtlisi** [comment]
I have a separate collector that implements collection from a pid file here https://github.com/Staples-Inc/snap-plugin-collector-procstat. I have yet to add a pgrep type collection.
