### ISSUE TITLE
Successive errors on disappeared processes make task disabled

### ISSUE THREAD

**Issue by obourdon** [intelsdi-x/snap-plugin-collector-processes#19]
Running a task for several days on a system can lead to a disabled task

Investigating this issue in more depth showed the following errors in the snapd log output:
```
ERRO[2016-08-16T15:46:06+02:00] collector run error                           _module=scheduler-job block=run error=CollectMetrics call error : open /proc/XXX/io: no such file or directory job-type=collector
WARN[2016-08-16T15:45:36+02:00] Task failed                                   _block=spin _module=scheduler-task consecutive failure limit=10 consecutive failures=2 error=CollectMetrics call error : open /proc/XXXX/io: no such file or directory task-id=0e666fad-5c31-489c-a9e4-cafc0d02ee97 task-name=Task-0e666fad-5c31-489c-a9e4-cafc0d02ee97
```

In fact, between the time [this code](https://github.com/intelsdi-x/snap-plugin-collector-processes/blob/master/processes/procstat.go#L67) is executed and the time [any of other code like](https://github.com/intelsdi-x/snap-plugin-collector-processes/blob/master/processes/procstat.go#L76) is run the corresponding process might have disappeared from the system where metrics are gathered

You can easily reproduce this by running snapd as non root on a system an you will get errors like
```
ERRO[2016-08-16T15:46:06+02:00] collector run error                           _module=scheduler-job block=run error=CollectMetrics call error : open /proc/1/io: permission denied job-type=collector
 ```

which will produce the exact same effect.

Potential suggested fix, for any of [code parts like this one](https://github.com/intelsdi-x/snap-plugin-collector-processes/blob/master/processes/procstat.go#L79) call a log.Warning (optional but why not) and go on with the loop iterating over the other processes list

**Comment by elemoine** [comment]
The suggested fix sounds good to me. But I think we can even use `log.Debug` or `log.Info` rather than `log.Warning`.

**Comment by obourdon** [comment]
The more I think about it the less I feel for having any kind of log message as the info is kind of "meaningless" anyways.

Furthermore, calling log.Anything does not seem to work for this plugin so I guess it will require too much work for the final worth ...

Of course I am open to any other suggestion.

**Comment by elemoine** [comment]
> The more I think about it the less I feel for having any kind of log message as the info is kind of "meaningless" anyways.

Agree.

**Comment by katarzyna-z** [comment]
@obourdon Could you make a pull request with the fix for this issue? Now, I don't see the pull request with the fix this issue.

 I think that it is worth to have "messages" - either warning, info or debug. Could you test the fix with the newest snap? Snap should capture logs from plugins.

**Comment by obourdon** [comment]
@katarzyna-z as I am currently testing this, I did not create a formal pull request for now.

However the potential fix [has posted earlier above](https://github.com/obourdon/snap-plugin-collector-processes/commit/78346f937ff12a91955638bbf7bd96b1e41dd68e) (without the log messages for now)

For reference this is also available in my [private git repo as a separate branch](https://github.com/obourdon/snap-plugin-collector-processes/tree/fix_4_issue19)

Will create the PR shortly so that I can get other comments as the fix seems to be effectively working on my test bed

**Comment by obourdon** [comment]
cc: [@intelsdi-x/plugin-maintainers](https://github.com/orgs/intelsdi-x/teams/plugin-maintainers)

**Comment by IzabellaRaulin** [comment]
Resolved by https://github.com/intelsdi-x/snap-plugin-collector-processes/pull/20
